@extends('layout.layout')
@section('title', 'Terms and condition')

@section('content')

    <!-- Start Hero Section -->
    <x-hero subTitle='Modern & Beautiful' img='assets/images/destination_header_bg.jpeg' title='Terms and Condition' />
    <!-- End Hero Section -->

    <!-- Start About Section -->
    <section class="cs_about cs_style_1">
      <div class="cs_height_80 cs_height_lg_80"></div>
      <div class="container">
        <p class="text-justify">Thank you for accessing/shopping at  https://www.book365days.com/,. This site is owned by ---  https://www.book365days.com/, ---- (hereinafter referred to as “--Salasar Holidays---”). By accessing, shopping on this site, you indicate your unconditional acceptance of these terms & conditions. We reserve this right, in our sole discretion, to update or revise these terms & conditions. Continued use of the site following the posting of any changes to the ‘terms & conditions’, constitutes your acceptance of those changes. At “--Salasar Holidays---”, we try our best to create a space where you can explore and shop for all your favorite things in a safe and secure environment. All products and information displayed on “--Salasar Holidays---” constitutes an "invitation to offer". “--Salasar Holidays---” reserves the right to accept or reject your offer. Your order for purchase, constitutes your "offer" which shall be subject to the terms and conditions as listed below.</p>
        <h5> 1. Eligibility to use our site</h5>
        <p class="text-justify">Use of the Site is available only to persons who can legally enter into contracts under applicable laws. Persons who are "incompetent to contract", within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Site. “--Salasar Holidays---” reserves the right to terminate your access to the Site if it discovers that you are under the age of 18 years or suffers from any other disability, as recognized under Indian Contract Act, 1872.</p>
        <h5> 2. Membership</h5>
        <p class="text-justify">Although it's not essential to have an account to shop with “-- https://www.book365days.com/,---”, you can shop as a guest. As a member, you agree to provide true, accurate, current, and complete information about yourself as prompted by the site's registration form. Registration where prohibited under any law shall be void. “--Salasar Holidays---” reserves the right to revoke or terminate your registration for any reason at any time, without notice.</p>
         <h5> 3. Electronic Communications</h5>
         <p class="text-justify">When you use the site or send emails or other data, information or communicate to us, you agree and understand that you are communicating with us electronically and give your consent to receive communications electronically from us periodically, when required.</p>
       <h5> 4. Reviews, Feedback, Submissions</h5>
       <p class="text-justify">All reviews, comments, feedback, postcards, suggestions, ideas, and other submissions disclosed, submitted or offered to “--Salasar Holidays---” directly or otherwise disclosed, submitted or offered in connection with your use of this Site (collectively referred to "Comments") will remain “--Salasar Holidays---” property. Such disclosure, submission or offer of any comments shall constitute an assignment to “--Salasar Holidays---” of all worldwide rights, titles and interests in all copyrights and other intellectual properties in the comments,thus, it exclusively owns all such rights, titles and interests and shall not be limited in any way in its use, commercial or otherwise. “--Salasar Holidays---” will be entitled to use, reproduce, disclose, modify, adapt, create derivative works from, publish, display and distribute any comments you submit for any purpose whatsoever, without restriction and without compensating you in any way. “--Salasar Holidays---” is and shall be under no obligation (1) to maintain any Comments in confidence; or (2) to pay you any compensation for any Comments; or (3) to respond to any Comments. You agree that any comments submitted by you to the Site will not violate this policy or any right of any third party, including copyright, trademark, privacy or other personal or proprietary right(s), and will not cause injury to any person or entity. You further agree that no comments submitted by you to the site will be libelous or otherwise unlawful, threatening, abusive or obscene material, or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of "spam". “--Salasar Holidays---” does not regularly review posted comments, but does reserve the right (but not the obligation) to monitor and edit or remove any comment submitted to the Site. You grant “--Salasar Holidays---” the right to use the name that you submit in connection with any of the posted comments. You agree not to use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any Comments you submit. You are and shall remain solely responsible for the content of any comments you make and you agree to indemnify “--Salasar Holidays---” and its affiliates for all claims resulting from any Comments you submit, we take no responsibility and assume no liability for any comments submitted by you or any third part</p>
      <h6>Accuracy of Content/ Information of Products on the Web Site</h6>
      <p class="text-justify">While “-- https://www.book365days.com/,---” strives to provide accurate product and pricing information, typographical errors may occur. In the event that a product is listed at an incorrect price or with incorrect information due to an error in pricing or product information, “--Salasar Holidays---” shall have the right, on our sole discretion, to modify the price of the products, or information of the products or to refuse or cancel any orders placed for that product, unless the product has already been dispatched. In the event.</p>
       <p class="text-justify">RefundAt  https://www.book365days.com/,, we strive to offer flexible travel solutions; however, all refunds are governed by the policies of the respective airline, hotel, or primary service provider associated with your booking. Salasar Holidays serves as an intermediary, facilitating bookings with third-party providers, and is bound by their terms and conditions regarding refunds, cancellations, and changes. Refund eligibility, processing times, and any applicable fees are determined by the specific policies of each provider. Salasar Holidays cannot guarantee refunds beyond the terms set by these airlines, hotels, or other service providers, and any requests for refunds must comply with their established procedures. Before finalizing a booking, we strongly recommend reviewing the cancellation and refund policies of each service provider to ensure they meet your needs. For assistance with a refund request or to better understand provider terms, please contact our support team. We appreciate your understanding and thank you for choosing Salasar Holidays.</p>
      </div>
      <div class="cs_height_80 cs_height_lg_80"></div>
    </section>
    <style>
      .container p {
        text-align: justify;
      }
    </style>
  @endsection